export const productData = [
  {
    id: 1,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMx0SX6Qeb9TlG1QZBL5sm_1D299W7mlb1lJKNqm4H55xTPsSXXUz8hgHL-iTc9Sz96Y0&usqp=CAU',
    name: 'Pure & Black Sleeve',
    price: 91.89,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 2,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMx0SX6Qeb9TlG1QZBL5sm_1D299W7mlb1lJKNqm4H55xTPsSXXUz8hgHL-iTc9Sz96Y0&usqp=CAU',
    name: "Levi's Red Florence",
    price: 78.34,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 3,
    img: 'https://st.depositphotos.com/1017986/2626/i/450/depositphotos_26263587-stock-photo-man-in-blank-t-shirt.jpg',
    name: 'Black & Curve Cooler',
    price: 899.34,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 4,
    img: 'https://st.depositphotos.com/1017986/2626/i/450/depositphotos_26263587-stock-photo-man-in-blank-t-shirt.jpg',
    name: 'Pure & Black Sleeve',
    price: 232.34,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 5,
    img: 'https://i.pinimg.com/736x/c6/c5/32/c6c532661c1cbb974dc59aa93df0a217.jpg',
    name: 'Red & Blue T-shirt',
    price: 84.23,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 6,
    img: 'https://i.pinimg.com/736x/c6/c5/32/c6c532661c1cbb974dc59aa93df0a217.jpg',
    name: 'Pure & Black Sleeve',
    price: 23.87,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 7,
    img: 'https://i.pinimg.com/736x/c6/c5/32/c6c532661c1cbb974dc59aa93df0a217.jpg',
    name: 'Gray With Sleeve',
    price: 105.50,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 8,
    img: 'https://i.pinimg.com/736x/c6/c5/32/c6c532661c1cbb974dc59aa93df0a217.jpg',
    name: 'Navi Blue',
    price: 45.80,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 9,
    img: 'https://i.pinimg.com/736x/c6/c5/32/c6c532661c1cbb974dc59aa93df0a217.jpg',
    name: 'Pure & Black Sleeve',
    price: 50.50,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 10,
    img: 'https://bwbo0zzm.cdn.imgeng.in/images/rlbee0fm/production/fa5692497dd2fa4e96148b9d5fea3df4dc833239-1501x2000.jpg?imgeng=w_1200/cmpr_40%201200w',
    name: 'Gray With Sleeve',
    price: 105.60,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 11,
    img: 'https://bwbo0zzm.cdn.imgeng.in/images/rlbee0fm/production/fa5692497dd2fa4e96148b9d5fea3df4dc833239-1501x2000.jpg?imgeng=w_1200/cmpr_40%201200w',
    name: 'Navi Blue',
    price: 45.56,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 12,
    img: 'https://www.dhresource.com/0x0/f2/albu/g22/M01/4C/18/rBNaEmJXub2ACpRNAABlPZxDr48965.jpg',
    name: 'Pure & Black Sleeve',
    price: 50.00,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 13,
    img: 'https://www.dhresource.com/0x0/f2/albu/g22/M01/4C/18/rBNaEmJXub2ACpRNAABlPZxDr48965.jpg',
    name: 'Gray With Sleeve',
    price: 106.50,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 14,
    img: 'https://www.dhresource.com/0x0/f2/albu/g22/M01/4C/18/rBNaEmJXub2ACpRNAABlPZxDr48965.jpg',
    name: 'Navi Blue',
    price: 46.80,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
  {
    id: 15,
    img: 'https://www.dhresource.com/0x0/f2/albu/g22/M01/4C/18/rBNaEmJXub2ACpRNAABlPZxDr48965.jpg',
    name: 'Pure & Black Sleeve',
    price: 50.00,
    details: 'Hot Collection Stylish and Fashionable Low Top Winter and Summer Exclusive Converse Sneakers for Men - Comfortable and Suitable for All',
  },
];
